name: MicroProfile Starter Tests

on:
  push:
    paths-ignore:
     - 'Container/**'
     - '.circleci/**'
     - 'CONTRIBUTING.md'
     - 'LICENSE'
     - 'README.md'
     - 'commands.txt'
     - 'gencerts.sh'
     - 'how-to.md'
     - 'releasing.md'
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths-ignore:
     - 'Container/**'
     - '.circleci/**'
     - 'CONTRIBUTING.md'
     - 'LICENSE'
     - 'README.md'
     - 'commands.txt'
     - 'gencerts.sh'
     - 'how-to.md'
     - 'releasing.md'

env:
  LANG: en_US.UTF-8
  JAVA_HOME: ${{ github.workspace }}/openjdk
  
jobs:
  run-starter:
    name: MicroProfile Starter build and test - ${{ matrix.jdk }}
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        jdk: ['OpenJDK11-latest-GA']
        include:
          - jdk: 'OpenJDK11-latest-GA'
            release_type: 'ga'
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
        path: starter
    - uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Get OpenJDK 11
      run: |
        curl -sL https://api.adoptopenjdk.net/v3/binary/latest/11/${{ matrix.release_type }}/linux/x64/jdk/hotspot/normal/openjdk -o jdk.tar.gz
        mkdir -p ${JAVA_HOME}
        tar xf jdk.tar.gz -C ${JAVA_HOME} --strip-components=1
        echo ${JAVA_HOME}
        ${JAVA_HOME}/bin/java --version
    - name: Build and run tests for Starter
      run: |
        cd ${{ github.workspace }}
        export PATH=${JAVA_HOME}/bin:${PATH}
        mvn clean verify -Pthorntail
    - name: Prepare failure archive (if maven failed)
      if: failure()
      shell: bash
      run: find . -type d -name '*-reports' -o -wholename '*/build/reports/tests/functionalTest' -o -name "*.log" | tar -czf test-reports.tgz -T -
    - name: Upload failure Archive (if maven failed)
      uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: test-reports
        path: 'test-reports.tgz'
 
